package Models;

public enum RevisionType {
    DEFENDANT_CHECK,
    SMALL_ORG_CHECK,
    ACCOUNT_CHECK,
    PASSPORT_CHECK,
    REG_DATE_CHECK,
    FZ115_CHECK,
    MMZ_CHECK,
    MANUAL_MFO_CHECK,
    LIMITS_CHECK,
    OVERDUE_CHECK,
    LAST_DATE_CREDITED_CHECK,
    FINAL_BORROWER_CHECK
}
